tmptmptext = strvcat('                                  EEGLAB 1997-2010 (compiled version)', ...
                  '       ', ...
                  '       ', ...
                  'The EEGLAB electrophysiological data analysis software is an open source research', ...
                  'project developped at the Swartz Center for Computational Neuroscience, Institute', ...
                  'for Neural Computation at the University of California San Diego in collaboration', ...
                  'with The Salk Institute (La Jolla) and the CERCO laboratory (Toulouse) where part', ...
                  'of the core code was developped.', ...
                  ' ', ...
                  'EEGLAB incorporates several third party suites of functions, Fieldtrip for source ', ...
                  'localization, and BIOSIG for binary file import. A list of plugins is also included', ...
                  'in this compiled release. See http://sccn.ucsd.edu/eeglab/plugins.html for more', ...
                  'information.', ...
                  ' ', ...
                  'The EEGLAB software, its source code, and the source code of all additional third', ... 
                  'party functions it includes is protected by the GNU GPL open source license.', ...
                  ' ');

warndlg2(tmptmptext);
clear tmptmptext;
