tmptmptext = strvcat('                                               EEGLAB 1997-2009', ...
                  '       ', ...
                  'The EEGLAB electrophysiological data analysis software is an open source research', ...
                  'project developped at the Swartz Center for Computational Neuroscience, Institute', ...
                  'for Neural Computation at the University of California San Diego in collaboration', ...
                  'with The Salk Institute (La Jolla) and the CERCO laboratory (Toulouse) where part', ...
                  'of the core code was developped.', ...
                  ' ', ...
                  'The EEGLAB software and source code is protected by the GNU GPL open source license.', ...
                  'No code may be copied or modified to be incorporated into commercial software', ...
                  ' ');

warndlg2(tmptmptext);
clear tmptmptext;