%Graphic interface builder functions (guifunc folder):
%  <a href="matlab:helpwin errordlg2">errordlg2</a>            - Makes a popup dialog box with the specified message and (optional)...
%  <a href="matlab:helpwin finputcheck">finputcheck</a>          - Check Matlab function {'key','value'} input argument pairs...
%  <a href="matlab:helpwin inputdlg2">inputdlg2</a>            - Inputdlg function clone with coloring and help for...
%  <a href="matlab:helpwin inputgui">inputgui</a>             - A comprehensive gui automatic builder. This function helps...
%  <a href="matlab:helpwin listdlg2">listdlg2</a>             - Listdlg function clone with coloring and help for...
%  <a href="matlab:helpwin pophelp">pophelp</a>              - Same as matlab HTHELP but does not crash under windows.
%  <a href="matlab:helpwin questdlg2">questdlg2</a>            - Questdlg function clone with coloring and help for...
%  <a href="matlab:helpwin supergui">supergui</a>             - A comprehensive gui automatic builder. This function help...
%  <a href="matlab:helpwin warndlg2">warndlg2</a>             - Same as warndlg for eeglab()...
