%EEGLAB statistics functions (statistics folder):
%  <a href="matlab:helpwin anova1_cell">anova1_cell</a>          - Compute F-values in cell array using ANOVA.
%  <a href="matlab:helpwin anova1rm_cell">anova1rm_cell</a>        - Compute F-values in cell array using repeated measure...
%  <a href="matlab:helpwin anova2_cell">anova2_cell</a>          - Compute F-values in cell array using ANOVA.
%  <a href="matlab:helpwin anova2rm_cell">anova2rm_cell</a>        - Compute F-values in cell array using repeated measure...
%  <a href="matlab:helpwin concatdata">concatdata</a>           - Concatenate data stored into a cell array into a single...
%  <a href="matlab:helpwin corrcoef_cell">corrcoef_cell</a>        - Compute pairwise correlations using arrays and...
%  <a href="matlab:helpwin fdr">fdr</a>                  - Compute false detection rate mask...
%  <a href="matlab:helpwin stat_surrogate_ci">stat_surrogate_ci</a>    - Vals under the null hypothesis that observed samples...
%  <a href="matlab:helpwin stat_surrogate_pvals">stat_surrogate_pvals</a> - Vals under the null hypothesis that observed samples...
%  <a href="matlab:helpwin statcond">statcond</a>             - Compare two or more data conditions statistically using...
%  <a href="matlab:helpwin statcondfieldtrip">statcondfieldtrip</a>    - Same as statcond except that it uses the fieldtrip...
%  <a href="matlab:helpwin surrogdistrib">surrogdistrib</a>        - Build surrogate distribution...
%  <a href="matlab:helpwin teststat">teststat</a>             - EEGLAB statistical testing function...
%  <a href="matlab:helpwin ttest2_cell">ttest2_cell</a>          - Compute unpaired t-test. Allow fast computation of...
%  <a href="matlab:helpwin ttest_cell">ttest_cell</a>           - Compute paired t-test. Allow fast computation of...
